version: '3.4'

services:
  
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  vehicleservice.api:
    image: ${DOCKER_REGISTRY-}vehicleserviceapi
    build:
      context: .
      dockerfile: VehicleService.API/Dockerfile
    depends_on:
      - sqldata

  idp:
    image: ${DOCKER_REGISTRY-}idp
    build:
      context: .
      dockerfile: Idp/Dockerfile
    depends_on:
      - sqldata

