version: '3.4'

services:
  
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 
  rabbitmq:
    image: rabbitmq:3-management-alpine

  vehicleservice.api:
    image: ${DOCKER_REGISTRY-}vehicleserviceapi
    build:
      context: .
      dockerfile: VehicleService.API/Dockerfile
    depends_on:
      - sqldata
      - idp

  idp:
    image: ${DOCKER_REGISTRY-}idp
    build:
      context: .
      dockerfile: Idp/Dockerfile
    depends_on:
      - sqldata 
  clientappmvc:
    image: ${DOCKER_REGISTRY-}clientappmvc
    build:
      context: .
      dockerfile: ClientAppMvc/Dockerfile
    ports:
      - "5030:80"
    depends_on:
      - idp
      - vehicleservice.api
  
  webhooks:
    image: ${DOCKER_REGISTRY-}webhooks
    build:
        context: .
        dockerfile: WebHooks.API/Dockerfile
    depends_on:
        - sqldata
        - vehicleservice.api
        - rabbitmq